Repository KernelSquare/Frontend, pull requests merged in 2024-02, with the labels that each got.

#72 feat: 프로필 정보 수정 관련 API 변동 사항 반영
  src/assets/images/basic.ts
  src/constants/response/member.ts
  src/interfaces/dto/member/update-member-introduction.dto.ts
  src/interfaces/dto/member/update-member-profile-image-dto.ts
  src/mocks/handler/member.ts
  src/page/user-profile/components/UserProfileMenu.tsx
  src/page/user-profile/components/UserProfilePresenter.tsx
  src/page/user-profile/components/introduction/Introduction.tsx
  src/page/user-profile/components/profileImage/ProfileImage.tsx
  src/page/user-profile/hooks/useIntroduction.tsx
  src/page/user-profile/hooks/useProfileImage.tsx
  src/react-query/member.ts
  src/service/member.ts
  src/service/route-map.ts
Labels: Refactor

#73 feat: 마이페이지 회원 정보 관련 수정 사항 반영
  src/components/shared/button/Button.tsx
  src/components/shared/confirm-modal/ConfirmModalMessage.ts
  src/components/shared/markdown/Editor/MarkdownEditor.tsx
  src/components/shared/markdown/Editor/ToolbarItems.ts
  src/constants/editor.ts
  src/constants/message.ts
  src/hooks/useToastUiEditorImageUploadHook.tsx
  src/interfaces/dto/auth/login.dto.ts
  src/interfaces/dto/member/update-member-info.dto.ts
  src/mocks/handler/member.ts
  src/page/askQuestion/components/editor/ContentEditor.tsx
  src/page/qna-detail/components/Answers/AnswerContentBox.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/user-profile/components/UserProfileMenu.tsx
  src/page/user-profile/components/introduction/Introduction.tsx
  src/page/user-profile/components/introduction/Introduction.types.ts
  src/page/user-profile/components/introduction/MdEditor.tsx
  src/page/user-profile/components/introduction/MdEditor.types.ts
  src/page/user-profile/components/introduction/MdViewer.tsx
  src/page/user-profile/components/profileImage/ProfileImage.tsx
  src/page/user-profile/components/profileImage/ProfileImage.types.ts
  src/page/user-profile/hooks/useIntroduction.types.ts
  src/page/user-profile/hooks/useProfileImage.tsx
  src/page/user-profile/hooks/useProfileImage.types.ts
  src/react-query/member.ts
  src/recoil/atoms/answerEditor.tsx
  src/recoil/atoms/introductionEditor.tsx
  src/recoil/atoms/questionEditor.tsx
  src/recoil/atoms/user.tsx
  src/service/member.ts
  src/service/route-map.ts
Labels: Feature, Refactor, fix

#76 feat: 채팅 구현
  package.json
  pnpm-lock.yaml
  public/timerWorker.js
  src/app/chat/_components/ChatError.tsx
  src/app/chat/_components/Layout.tsx
  src/app/chat/room/[id]/page.tsx
  src/app/question/page.tsx
  src/app/question/u/[id]/page.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/navigation/Navigation.tsx
  src/components/shared/Profile.tsx
  src/components/ui/Select.tsx
  src/constants/editor.ts
  src/constants/layoutMeta.ts
  src/constants/response/coffeechat.ts
  src/hooks/time/useStopwatch.tsx
  src/interfaces/code-highlight.d.ts
  src/interfaces/dto/coffee-chat/enter-chat-room.ts
  src/mocks/db/questions.ts
  src/mocks/handler/coffee-chat.ts
  src/page/askQuestion/components/AskQuestionForm.tsx
  src/page/askQuestion/components/AskQuestionPageControl.tsx
  src/page/coffee-chat/chat/ChatRoom.tsx
  src/page/coffee-chat/chat/ChatRoomHeader.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat.tsx
  src/page/coffee-chat/main/CoffeeChatWelcome.tsx
  src/recoil/atoms/socket/socketAtom.tsx
  src/service/coffee-chat.ts
  src/service/route-map.ts
  src/socket/client/MessageControl.tsx
  src/socket/client/Messages.tsx
  src/socket/client/SocketConnection.tsx
  src/socket/client/code/CodeEditor.tsx
  src/socket/client/code/CodeLanguageSelect.tsx
  src/socket/provider.ts
  src/socket/server/sockjsServer.js
  src/util/getDate.ts
  src/util/layoutMeta.ts
  tailwind.config.ts
Labels: Feature

#79 feat: 채팅 기능 구현
  package.json
  pnpm-lock.yaml
  public/timerWorker.js
  src/app/chat/_components/ChatError.tsx
  src/app/chat/_components/Layout.tsx
  src/app/chat/room/[id]/page.tsx
  src/app/question/page.tsx
  src/app/question/u/[id]/page.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/navigation/Navigation.tsx
  src/components/shared/Profile.tsx
  src/components/ui/Select.tsx
  src/constants/editor.ts
  src/constants/layoutMeta.ts
  src/constants/response/coffeechat.ts
  src/hooks/time/useStopwatch.tsx
  src/interfaces/code-highlight.d.ts
  src/interfaces/dto/coffee-chat/enter-chat-room.ts
  src/mocks/db/questions.ts
  src/mocks/handler/answer.ts
  src/mocks/handler/coffee-chat.ts
  src/page/askQuestion/components/AskQuestionForm.tsx
  src/page/askQuestion/components/AskQuestionPageControl.tsx
  src/page/coffee-chat/chat/ChatRoom.tsx
  src/page/coffee-chat/chat/ChatRoomHeader.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat.tsx
  src/page/coffee-chat/main/CoffeeChatWelcome.tsx
  src/page/qna-detail/QnADetail.tsx
  src/page/user-profile/components/UserProfileMenu.tsx
  src/page/user-profile/components/profileImage/ProfileImage.tsx
  src/react-query/answers.ts
  src/recoil/atoms/socket/socketAtom.tsx
  src/service/coffee-chat.ts
  src/service/route-map.ts
  src/socket/client/MessageControl.tsx
  src/socket/client/Messages.tsx
  src/socket/client/SocketConnection.tsx
  src/socket/client/code/CodeEditor.tsx
  src/socket/client/code/CodeLanguageSelect.tsx
  src/socket/provider.ts
  src/socket/server/sockjsServer.js
  src/util/getDate.ts
  src/util/layoutMeta.ts
  tailwind.config.ts
Labels: Feature, fix

#83 feat: 회원탈퇴
  package.json
  src/app/chat/_components/ChatError.tsx
  src/app/chat/room/[id]/page.tsx
  src/app/not-found.tsx
  src/app/profile/[id]/_components/deleteMember/DeleteMemberModal.tsx
  src/app/profile/[id]/_components/deleteMember/DeleteMemberModalHeader.tsx
  src/app/profile/[id]/_components/deleteMember/steps/ConfirmStep.tsx
  src/app/profile/[id]/_components/deleteMember/steps/IntroStep.tsx
  src/app/profile/[id]/_components/deleteMember/steps/ReasonFormStep.tsx
  src/app/profile/[id]/_components/deleteMember/steps/SubmitStep.tsx
  src/components/layout/header/UserArea.tsx
  src/components/layout/navigation/Navigation.tsx
  src/components/layout/navigation/NavigationTab.tsx
  src/components/layout/navigation/SideNavigation.tsx
  src/components/shared/funnel/Funnel.tsx
  src/components/shared/radio/Radio.tsx
  src/constants/navigationRoute.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat.tsx
  src/page/user-profile/components/UserProfileMenu.tsx
  src/page/user-profile/components/introduction/Introduction.tsx
  src/recoil/atoms/popup/popupWindowAtom.tsx
  src/recoil/atoms/user.tsx
  src/socket/client/SocketConnection.tsx
  src/socket/server/sockjsServer.js
  src/util/layoutMeta.ts
Labels: Feature, fix

#102 fix: 버그 fix
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat.tsx
  src/socket/client/MessageControl.tsx
  src/util/validate.ts
Labels: bug, Feature

#104 fix: QA 오류 사항 수정
  src/components/layout/header/search/SearchArea.tsx
  src/components/layout/header/search/SearchModal.tsx
  src/components/shared/toast-ui-editor/editor/Editor.tsx
  src/constants/message.ts
  src/mocks/db/answers.ts
  src/mocks/db/user.ts
  src/mocks/handler/answer.ts
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/create/components/CustomCalendar/CustomCalendar.tsx
  src/page/coffee-chat/create/components/ScheduleSection.tsx
  src/page/coffee-chat/create/hooks/useGetScheduleList.tsx
  src/page/qna-detail/QnADetail.tsx
  src/page/qna-detail/components/Answers/VoteBox.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/qna-detail/hooks/useAnswerVote.tsx
  src/page/qna-detail/hooks/useHandleMyAnswer.tsx
  src/page/qna-detail/hooks/useQnADetail.tsx
  src/page/user-profile/components/introduction/Introduction.tsx
  src/react-query/answers.ts
  src/recoil/atoms/mode.tsx
Labels: fix

#110 feat: faq, 네비게이션
  src/app/faq/page.tsx
  src/app/notice/page.tsx
  src/components/layout/header/UserArea.tsx
  src/constants/layoutMeta.ts
  src/constants/navigationRoute.tsx
  src/page/FaQ.tsx
  src/page/faq/FaQPage.tsx
Labels: Feature

#111 fix: QA 수정 2차 반영
  src/app/not-found.tsx
  src/assets/lottie/not-found.json
  src/components/shared/animation/NotFound.tsx
  src/page/notFound/PageNotFound.tsx
  src/page/qna-detail/QnADetail.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/hooks/useToastUiEditorImageUploadHook.tsx
  src/service/route-map.ts
Labels: fix

#112 chore: merge
  src/app/chat/_components/ChatError.tsx
  src/app/chat/_components/Layout.tsx
  src/app/faq/page.tsx
  src/app/not-found.tsx
  src/app/notice/page.tsx
  src/assets/lottie/not-found.json
  src/components/layout/header/UserArea.tsx
  src/components/layout/header/search/SearchArea.tsx
  src/components/layout/header/search/SearchModal.tsx
  src/components/shared/animation/NotFound.tsx
  src/components/shared/tag/SelectableTagList.tsx
  src/components/shared/toast-ui-editor/editor/Editor.tsx
  src/constants/layoutMeta.ts
  src/constants/message.ts
  src/constants/navigationRoute.tsx
  src/hooks/useSelectTagList.tsx
  src/mocks/db/answers.ts
  src/mocks/db/user.ts
  src/mocks/handler/answer.ts
  src/page/FaQ.tsx
  src/page/askQuestion/components/AskQuestionForm.tsx
  src/page/askQuestion/components/CancelAskQuestionModal.tsx
  src/page/coffee-chat/chat/ChatRoom.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/create/components/CustomCalendar/CustomCalendar.tsx
  src/page/coffee-chat/create/components/ScheduleSection.tsx
  src/page/coffee-chat/create/hooks/useGetScheduleList.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat.tsx
  src/page/faq/FaQPage.tsx
  src/page/notFound/PageNotFound.tsx
  src/page/qna-detail/QnADetail.tsx
  src/page/qna-detail/components/Answers/VoteBox.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/qna-detail/hooks/useAnswerVote.tsx
  src/page/qna-detail/hooks/useHandleMyAnswer.tsx
  src/page/qna-detail/hooks/useQnADetail.tsx
  src/page/qna-detail/hooks/useToastUiEditorImageUploadHook.tsx
  src/page/user-profile/components/introduction/Introduction.tsx
  src/react-query/answers.ts
  src/recoil/atoms/mode.tsx
  src/recoil/atoms/tag.tsx
  src/service/question.ts
  src/service/route-map.ts
  src/socket/client/MessageControl.tsx
  src/socket/client/Messages.tsx
  src/socket/client/SocketConnection.tsx
  src/util/getDate.ts
  src/util/validate.ts
Labels: Feature

#113 Feat/frontend#90
  src/page/coffee-chat/create/components/ScheduleSection.tsx
  src/page/coffee-chat/create/hooks/useGetScheduleList.tsx
Labels: fix

#114 fix: 예약 생성 시 날짜 관련 이슈 해결
  src/page/coffee-chat/create/components/ScheduleSection.tsx
  src/page/coffee-chat/create/hooks/useGetScheduleList.tsx
Labels: fix

#115 fix: 마크다운 Viewer 절대경로로 수정
  src/mocks/db/coffee-chat.ts
  src/page/coffee-chat/detail/CoffeeChatDetailContent.tsx
  src/page/qna-detail/components/Markdown/MdViewer.tsx
  src/page/user-profile/components/introduction/MdViewer.tsx
  src/util/editor.ts
Labels: fix

#116 fix: 마크다운 Viewer 절대경로로 수정
  src/mocks/db/coffee-chat.ts
  src/page/coffee-chat/detail/CoffeeChatDetailContent.tsx
  src/page/qna-detail/components/Markdown/MdViewer.tsx
  src/page/user-profile/components/introduction/MdViewer.tsx
  src/util/editor.ts
Labels: fix

#118 fix: 입장하기 비활성화
  src/page/coffee-chat/detail/EnterCoffeeChat.tsx
Labels: fix

#124 fix: 태그 UI, 카드 UI 수정
  src/components/shared/tag/HashTag.tsx
  src/components/shared/tag/Tag.tsx
  src/page/coffee-chat/main/CoffeeChatList.tsx
  src/page/qna/components/QnAList.tsx
Labels: design

#126 fix: 회원가입 유효성 수정
  src/components/shared/input/Guideline.tsx
  src/page/signup/Signup.tsx
  src/util/validate.ts
Labels: Feature, fix

#127 fix: placeholder 페이지별 수정 및 toastify limit 설정
  src/app/layout.tsx
  src/components/layout/header/search/SearchArea.tsx
  src/components/layout/header/search/SearchModal.tsx
  src/components/shared/markdown/Editor/MarkdownEditor.tsx
  src/components/shared/toast-ui-editor/editor/Editor.tsx
  src/mocks/handler/answer.ts
  src/mocks/handler/coffee-chat.ts
  src/mocks/handler/member.ts
  src/page/askQuestion/CancelUploadImage.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/create/components/MdEditor.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailHeader.tsx
  src/page/coffee-chat/detail/reservation/mentor/ReservationForMentor.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/hooks/useHandleQuestion.tsx
  src/page/user-profile/components/introduction/MdEditor.tsx
Labels: Refactor

#129 fix: 페이지네이션 수정
  .github/workflows/ci-workflow.yml
  Dockerfile
  src/components/shared/pagination/Pagination.tsx
  src/page/qna/QnA.tsx
Labels: design

#137 fix: ci yml 수정
  .github/workflows/ci-workflow.yml
Labels: Infra, fix

#160 feat: sentry 적용
  .gitignore
  next.config.js
  package.json
  pnpm-lock.yaml
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.jsx
Labels: Setting

#162 fix: CI 환경변수 추가
  .github/workflows/ci-workflow.yml
  Dockerfile
Labels: Setting, fix

#167 feat: 메인,qna 도메인 분리
  src/app/page.tsx
  src/app/qna/page.tsx
  src/components/layout/navigation/Navigation.tsx
  src/constants/layoutMeta.ts
  src/constants/navigationRoute.tsx
Labels: Feature

#171 refactor: API 수정 사항 및 데이터 제한 정책 반영
  src/constants/limitation.ts
  src/constants/message.ts
  src/constants/response/answer.ts
  src/constants/response/image.ts
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/create/components/HashTagsSection.tsx
  src/page/coffee-chat/create/components/TimeOptions.tsx
  src/page/coffee-chat/detail/reservation/mentee/TimeOptions.tsx
  src/page/qna-detail/components/Answers/AnswerContentBox.tsx
  src/page/qna-detail/components/Answers/AnswerList.tsx
  src/page/qna-detail/components/Answers/OneAnswer.tsx
  src/page/qna-detail/components/Answers/VoteBox.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/qna-detail/components/Question/HandleQuestionBox.tsx
  src/page/qna-detail/components/Question/Question.tsx
  src/page/qna-detail/hooks/useAnswerVote.tsx
  src/page/qna-detail/hooks/useHandleMyAnswer.tsx
  src/page/qna-detail/hooks/useHandleQuestion.tsx
  src/page/qna-detail/hooks/useQnADetail.tsx
  src/page/user-profile/components/UserProfilePresenter.tsx
  src/page/user-profile/components/introduction/MdViewer.tsx
  src/page/user-profile/components/profileImage/ProfileImage.tsx
  src/page/user-profile/hooks/useIntroduction.tsx
  src/page/user-profile/hooks/useProfileImage.tsx
Labels: Refactor, fix

#174 feat: 모각코 생성 등 관련 API 타입 및 msw 로직 구현
  src/constants/message.ts
  src/constants/response/api.ts
  src/constants/response/coding-meetings.ts
  src/interfaces/coding-meetings.ts
  src/interfaces/dto/coding-meeting/create-coding-meeting.dto.ts
  src/interfaces/dto/coding-meeting/delete-coding-meeting.dto.ts
  src/interfaces/dto/coding-meeting/get-coding-meetingl-list.dto.ts
  src/interfaces/dto/coding-meeting/update-coding-meeting.dto.ts
  src/mocks/db/coding-meetings.ts
  src/mocks/handler/coding-meeting.ts
  src/mocks/handler/index.ts
  src/service/coding-meetings.ts
  src/service/route-map.ts
Labels: Feature

#175 fix: 질문 작성 및 수정 제한 적용
  src/constants/limitation.ts
  src/constants/message.ts
  src/hooks/useToastUiEditorImageUploadHook.tsx
  src/page/askQuestion/components/AskQuestionForm.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/hooks/useToastUiEditorImageUploadHook.tsx
  src/page/user-profile/hooks/useProfileImage.tsx
Labels: Refactor, fix

#177 feat: 모각코 모집글 생성 페이지 기본 퍼블리싱 및 API 호출
  package.json
  pnpm-lock.yaml
  src/app/coding-meetings/create/page.tsx
  src/app/coding-meetings/post/page.tsx
  src/components/icons/Icons.tsx
  src/components/ui/Dialog.tsx
  src/components/ui/Select.tsx
  src/interfaces/coding-meetings.ts
  src/interfaces/dto/coding-meeting/create-coding-meeting.dto.ts
  src/mocks/db/coding-meetings.ts
  src/mocks/handler/coding-meeting.ts
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/create/CreateCodingMeetingPage.types.ts
  src/page/coding-meetings/create/CreatePage.tsx
  src/page/coding-meetings/create/components/CodingMeetingSection.tsx
  src/page/coding-meetings/create/components/CustomCalendar/Calendar.css
  src/page/coding-meetings/create/components/CustomCalendar/Calendar.types.ts
  src/page/coding-meetings/create/components/CustomCalendar/CustomCalendar.tsx
  src/page/coding-meetings/create/components/CustomMap/kakaoMap.tsx
  src/page/coding-meetings/create/components/DateTimeSection.tsx
  src/page/coding-meetings/create/components/HashTagsSection.tsx
  src/page/coding-meetings/create/components/HeadCountSection.tsx
  src/page/coding-meetings/create/components/LocationSection.tsx
  src/react-query/coding-meeting.ts
  src/recoil/atoms/coding-meeting/hashtags.tsx
  src/recoil/atoms/coding-meeting/headcount.tsx
  src/service/coding-meetings.ts
  tsconfig.json
Labels: Feature, design

#178 feat: 모각코 메인 페이지
  src/app/coding-meetings/page.tsx
  src/assets/codingMeetingInfo.svg
  src/components/shared/page-template/ListPage.tsx
  src/components/shared/page-template/page-info-area/PageInfoArea.tsx
  src/components/shared/pagination/Pagination.tsx
  src/interfaces/coding-meetings.ts
  src/interfaces/dto/coding-meeting/get-coding-meetingl-list.dto.ts
  src/mocks/db/coding-meetings.ts
  src/mocks/handler/coding-meeting.ts
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/main/MainPage.tsx
  src/page/coding-meetings/main/ScrollTopButton.tsx
  src/page/coding-meetings/main/Tab.tsx
  src/page/coding-meetings/main/coding-meeting-list/CodingMeetingList.tsx
  src/page/coding-meetings/main/coding-meeting-list/CodingMeetingListContainer.tsx
  src/page/coding-meetings/main/info-area/AreaImage.tsx
  src/page/coding-meetings/main/info-area/InfoArea.tsx
  src/page/user-profile/components/UserProfilePresenter.tsx
  src/service/coding-meetings.ts
  tailwind.config.ts
Labels: Feature, fix

#182 feat: 모각코 모집글 생성 페이지 구현
  src/components/icons/Icons.tsx
  src/constants/limitation.ts
  src/constants/message.ts
  src/constants/queryKey.ts
  src/constants/timeOptions.ts
  src/interfaces/calendar.ts
  src/interfaces/dto/coding-meeting/create-coding-meeting.dto.ts
  src/mocks/handler/coding-meeting.ts
  src/page/askQuestion/components/AskQuestionForm.tsx
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/create/components/CustomCalendar/CustomCalendar.tsx
  src/page/coding-meetings/create/components/CustomMap/kakaoMap.tsx
  src/page/coding-meetings/create/components/DateTimeSection.tsx
  src/page/coding-meetings/create/components/HeadCountSection.tsx
  src/page/coding-meetings/create/components/LocationSection.tsx
  src/react-query/coding-meeting.ts
  src/recoil/atoms/coding-meeting/dateTime.tsx
  src/recoil/atoms/coding-meeting/headcount.tsx
  src/recoil/atoms/coding-meeting/mapData.tsx
  src/recoil/atoms/coffee-chat/schedule.tsx
Labels: Feature

#184 hotfix: 채팅 reservation_id
  src/app/chat/_components/ChatError.tsx
  src/app/chat/room/[id]/page.tsx
  src/interfaces/dto/coffee-chat/enter-chat-room.ts
  src/page/coffee-chat/chat/ChatRoom.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat.tsx
  src/page/coffee-chat/detail/reservation/mentor/ReservationForMentor.tsx
  src/service/coffee-chat.ts
Labels: fix

#185 hotfix: 채팅
  src/mocks/handler/coffee-chat.ts
Labels: fix

#186 feat: 모각코 수정 페이지 구현 완료
  src/app/coding-meetings/create/page.tsx
  src/app/coding-meetings/post/[token]/page.tsx
  src/app/coding-meetings/post/page.tsx
  src/components/shared/auth-modal/AuthGuardModal.tsx
  src/components/shared/auth-modal/UpdateCodingMeetingGuardModal.tsx
  src/constants/response/coding-meetings.ts
  src/constants/select.ts
  src/interfaces/coding-meetings.ts
  src/interfaces/dto/coding-meeting/get-coding-meeting-detail.dto.ts
  src/interfaces/dto/coding-meeting/update-coding-meeting.dto.ts
  src/mocks/db/coding-meetings.ts
  src/mocks/handler/coding-meeting.ts
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/create/CreateCodingMeetingPage.types.ts
  src/page/coding-meetings/create/components/DateTimeSection.tsx
  src/page/coding-meetings/create/components/HashTagsSection.tsx
  src/page/coding-meetings/create/components/HeadCountSection.tsx
  src/page/coding-meetings/create/components/LocationSection.tsx
  src/page/coding-meetings/update/UpdatePage.tsx
  src/react-query/coding-meeting.ts
  src/recoil/atoms/coding-meeting/dateTime.tsx
  src/service/coding-meetings.ts
  src/service/route-map.ts
Labels: Feature

#188 feat: 모각코 상세
  src/app/coding-meetings/[token]/page.tsx
  src/constants/response/coding-meetings.ts
  src/interfaces/coding-meetings.ts
  src/interfaces/dto/coding-meeting/close-coding-meeting.dto.ts
  src/interfaces/dto/coding-meeting/comment/create-coding-meeting-comment.dto.ts
  src/interfaces/dto/coding-meeting/comment/delete-coding-meeting-comment.dto.ts
  src/interfaces/dto/coding-meeting/comment/get-coding-meeting-comment-list.dto.ts
  src/interfaces/dto/coding-meeting/comment/update-coding-meeting-comment.dto.ts
  src/mocks/db/coding-meetings.ts
  src/mocks/handler/coding-meeting.ts
  src/page/coding-meetings/detail/Comments.tsx
  src/page/coding-meetings/detail/DetailHeader.tsx
  src/page/coding-meetings/detail/DetailMenu.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/Map.tsx
  src/page/coding-meetings/detail/Section.tsx
  src/page/coding-meetings/detail/UserInfo.tsx
  src/page/coding-meetings/main/coding-meeting-list/CodingMeetingList.tsx
  src/service/coding-meetings.ts
  src/service/route-map.ts
  src/util/getDate.ts
Labels: Feature

#189 chore: hotfix 반영
  src/app/chat/_components/ChatError.tsx
  src/app/chat/room/[id]/page.tsx
  src/interfaces/dto/coffee-chat/enter-chat-room.ts
  src/mocks/handler/coffee-chat.ts
  src/page/coffee-chat/chat/ChatRoom.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat.tsx
  src/page/coffee-chat/detail/reservation/mentor/ReservationForMentor.tsx
  src/service/coffee-chat.ts
Labels: fix

#190 chore: docker , ci 수정
  .github/workflows/ci-workflow.yml
  Dockerfile
Labels: Infra, Setting

#199 fix: 상세 수정사항 반영 , 구글 폼 주소 수정
  src/page/coding-meetings/detail/Comments.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/UserInfo.tsx
  src/page/faq/FaQPage.tsx
Labels: fix

#200 fix: 상세 수정 사항 반영, 구글 폼 링크 주소 수정
  src/page/coding-meetings/detail/Comments.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/UserInfo.tsx
  src/page/faq/FaQPage.tsx
Labels: fix

#203 fix: 댓글 최소, 콘솔 적용
  src/page/coding-meetings/detail/Comments.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
Labels: fix

#204 fix: 댓글 최소, 상세페이지 시간 콘솔
  src/page/coding-meetings/detail/Comments.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
Labels: fix

#206 fix: 상세시간 렌더링 환경 수정
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/DetailTime.tsx
Labels: fix
