Repository KernelSquare/Frontend, pull requests merged in 2024-03, with the labels that each got.

#208 fix: 모각코 상세, 메인
  package.json
  pnpm-lock.yaml
  src/app/coding-meetings/[token]/page.tsx
  src/components/shared/page-template/ListPage.tsx
  src/components/ui/PopOver.tsx
  src/page/coding-meetings/detail/Comments.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/UserInfo.tsx
  src/page/coding-meetings/detail/kakao-map/Control.tsx
  src/page/coding-meetings/detail/kakao-map/KakaoMapError.tsx
  src/page/coding-meetings/detail/kakao-map/Map.tsx
  src/page/coding-meetings/detail/kakao-map/MapContainer.tsx
  src/page/coding-meetings/main/ScrollTopButton.tsx
Labels: Feature, fix

#209 chore: merge with dev
  package.json
  pnpm-lock.yaml
  src/app/coding-meetings/[token]/page.tsx
  src/components/shared/page-template/ListPage.tsx
  src/components/ui/PopOver.tsx
  src/page/coding-meetings/detail/Comments.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/UserInfo.tsx
  src/page/coding-meetings/detail/kakao-map/Control.tsx
  src/page/coding-meetings/detail/kakao-map/KakaoMapError.tsx
  src/page/coding-meetings/detail/kakao-map/Map.tsx
  src/page/coding-meetings/detail/kakao-map/MapContainer.tsx
  src/page/coding-meetings/main/ScrollTopButton.tsx
Labels: Feature, fix

#212 chore: merge with dev
  src/page/coding-meetings/main/coding-meeting-list/CodingMeetingList.tsx
Labels: fix

#217 feat: 공용 텍스트 길이 카운터
  src/components/shared/TextCounter.tsx
Labels: Feature

#218 fix: 2차 QA 피드백 반영
  src/app/coding-meetings/[token]/page.tsx
  src/components/layout/Layout.tsx
  src/components/layout/LayoutInner.tsx
  src/components/shared/Inner.tsx
  src/components/shared/confirm-modal/ConfirmModal.tsx
  src/constants/limitation.ts
  src/constants/message.ts
  src/constants/timeOptions.ts
  src/mocks/handler/coffee-chat.ts
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/create/components/CustomMap/kakaoMap.tsx
  src/page/coding-meetings/create/components/DateTimeSection.tsx
  src/page/coding-meetings/create/hooks/useHandleCreateCodingMeetingTime.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/reservation/mentee/TimeOptions.tsx
  src/page/landing/Landing.tsx
  src/page/landing/components/LandingHeader.tsx
  src/page/landing/components/LandingSearchBar.tsx
  src/page/qna-detail/components/Answers/AnswerContentBox.tsx
  src/page/qna-detail/components/Answers/AnswerList.tsx
  src/page/qna-detail/components/Answers/HandleAnswerBox.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/qna-detail/hooks/useHandleQuestion.tsx
  src/page/user-profile/components/UserProfileMenu.tsx
  src/page/user-profile/components/profileImage/ProfileImage.tsx
  src/page/user-profile/hooks/useProfileImage.tsx
  src/recoil/atoms/coding-meeting/dateTime.tsx
  src/util/checkFormValidation.ts
  src/util/getDate.ts
Labels: Refactor, fix

#219 fix: 2차 QA 반영
  src/app/layout.tsx
  src/components/form/LoginForm.tsx
  src/components/layout/ToastDismissListener.tsx
  src/components/layout/header/UserArea.tsx
  src/components/shared/page-template/ListPage.tsx
  src/components/shared/tag/SelectableTagList.tsx
  src/hooks/coding-meeting/useCommentMutation.tsx
  src/mocks/db/coding-meetings.ts
  src/mocks/handler/coding-meeting.ts
  src/page/coding-meetings/detail/DetailMenu.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/comment/CommentContent.tsx
  src/page/coding-meetings/detail/comment/CommentControl.tsx
  src/page/coding-meetings/detail/comment/Comments.tsx
  src/page/coding-meetings/detail/modal/CodingMeetingClose.tsx
  src/page/coding-meetings/detail/modal/CodingMeetingCloseConfirm.tsx
  src/page/coding-meetings/main/info-area/QnAInfoArea.tsx
  src/page/qna/QnA.tsx
  src/page/qna/components/QnAList.tsx
  src/page/qna/components/QnAListMenu.tsx
  src/page/qna/components/QuestionListContainer.tsx
  src/page/signup/Signup.tsx
  src/page/signup/components/ProgressModal.tsx
  src/recoil/atoms/coding-meeting/comment.tsx
  src/service/coding-meetings.ts
Labels: Feature, fix

#220 fix: 2차QA 반영
  src/app/coding-meetings/[token]/page.tsx
  src/app/layout.tsx
  src/components/form/LoginForm.tsx
  src/components/layout/Layout.tsx
  src/components/layout/LayoutInner.tsx
  src/components/layout/ToastDismissListener.tsx
  src/components/layout/header/UserArea.tsx
  src/components/shared/Inner.tsx
  src/components/shared/TextCounter.tsx
  src/components/shared/confirm-modal/ConfirmModal.tsx
  src/components/shared/page-template/ListPage.tsx
  src/components/shared/tag/SelectableTagList.tsx
  src/constants/limitation.ts
  src/constants/message.ts
  src/constants/timeOptions.ts
  src/hooks/coding-meeting/useCommentMutation.tsx
  src/mocks/db/coding-meetings.ts
  src/mocks/handler/coding-meeting.ts
  src/mocks/handler/coffee-chat.ts
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/create/components/CustomMap/kakaoMap.tsx
  src/page/coding-meetings/create/components/DateTimeSection.tsx
  src/page/coding-meetings/create/hooks/useHandleCreateCodingMeetingTime.tsx
  src/page/coding-meetings/detail/DetailMenu.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/comment/CommentContent.tsx
  src/page/coding-meetings/detail/comment/CommentControl.tsx
  src/page/coding-meetings/detail/comment/Comments.tsx
  src/page/coding-meetings/detail/modal/CodingMeetingClose.tsx
  src/page/coding-meetings/detail/modal/CodingMeetingCloseConfirm.tsx
  src/page/coding-meetings/main/info-area/QnAInfoArea.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/reservation/mentee/TimeOptions.tsx
  src/page/landing/Landing.tsx
  src/page/landing/components/LandingHeader.tsx
  src/page/landing/components/LandingSearchBar.tsx
  src/page/qna-detail/components/Answers/AnswerContentBox.tsx
  src/page/qna-detail/components/Answers/AnswerList.tsx
  src/page/qna-detail/components/Answers/HandleAnswerBox.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/qna-detail/hooks/useHandleQuestion.tsx
  src/page/qna/QnA.tsx
  src/page/qna/components/QnAList.tsx
  src/page/qna/components/QnAListMenu.tsx
  src/page/qna/components/QuestionListContainer.tsx
  src/page/signup/Signup.tsx
  src/page/signup/components/ProgressModal.tsx
  src/page/user-profile/components/UserProfileMenu.tsx
  src/page/user-profile/components/profileImage/ProfileImage.tsx
  src/page/user-profile/hooks/useProfileImage.tsx
  src/recoil/atoms/coding-meeting/comment.tsx
  src/recoil/atoms/coding-meeting/dateTime.tsx
  src/service/coding-meetings.ts
  src/util/checkFormValidation.ts
  src/util/getDate.ts
Labels: Feature, fix

#223 fix: 질문 작성 링크주소 수정
  src/components/form/LoginForm.tsx
  src/page/coding-meetings/main/info-area/QnAInfoArea.tsx
Labels: fix

#224 fix: 질문 작성 링크 주소, 로그인 중 문구
  src/components/form/LoginForm.tsx
  src/page/coding-meetings/main/info-area/QnAInfoArea.tsx
Labels: fix

#226 fix: 질문 작성 취소 이후 이동 주소 수정
  src/page/askQuestion/components/CancelAskQuestionModal.tsx
Labels: fix

#227 fix: 검수 피드백 반영
  src/components/shared/auth-modal/MyPageGuardModal.tsx
  src/components/shared/auth-modal/UserProfileGuardModal.tsx
  src/constants/timeOptions.ts
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/create/hooks/useHandleCreateCodingMeetingTime.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.types.ts
  src/page/coffee-chat/create/components/HashTagsSection.tsx
  src/page/coffee-chat/create/components/MdEditor.tsx
  src/page/coffee-chat/create/components/ScheduleSection.tsx
  src/page/coffee-chat/create/components/TimeOptions.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/qna-detail/components/Answers/AnswerContentBox.tsx
  src/page/user-profile/components/introduction/Introduction.tsx
  src/page/user-profile/components/introduction/MdEditor.tsx
Labels: fix

#230 fix: 페이지네이션 적용, 검색 페이지 gap 수정
  src/components/shared/pagination/Pagination.tsx
  src/components/shared/qna/QnAList.tsx
  src/page/coffee-chat/main/CoffeeChatListContainer.tsx
Labels: fix

#231 fix: 검수 피드백 반영
  src/components/shared/confirm-modal/ConfirmModal.tsx
  src/components/shared/confirm-modal/ConfirmModalMessage.ts
  src/constants/message.ts
  src/constants/message/confirmModal.ts
  src/mocks/db/coffee-chat.ts
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/create/components/CodingMeetingSection.tsx
  src/page/coding-meetings/create/components/CustomMap/kakaoMap.tsx
  src/page/coding-meetings/create/components/HashTagsSection.tsx
  src/page/coding-meetings/create/components/LocationSection.tsx
  src/page/coffee-chat/create/components/ScheduleSection.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterChatRoomArea.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
  src/page/coffee-chat/detail/reservation/mentee/ReservationForMentee.tsx
  src/page/coffee-chat/detail/reservation/mentee/TimeOptions.tsx
  src/page/coffee-chat/detail/reservation/mentor/ReservationForMentor.tsx
  src/page/landing/Landing.tsx
  src/page/landing/components/LandingSearchBar.tsx
  src/page/qna-detail/components/Answers/AnswerList.tsx
  src/page/user-profile/hooks/useProfileImage.tsx
  src/util/getDate.ts
Labels: Refactor, fix

#235 feat: AI 인턴 자동 응답 호출 기능 구현
  src/constants/response/answer.ts
  src/interfaces/answer.ts
  src/interfaces/dto/answer/create-AI-auto-answer.ts
  src/mocks/db/answers.ts
  src/mocks/db/user.ts
  src/mocks/handler/answer.ts
  src/page/askQuestion/components/AskQuestionForm.tsx
  src/page/qna-detail/components/Answers/OneAnswer.tsx
  src/react-query/answers.ts
  src/service/answers.ts
  src/service/route-map.ts
Labels: Feature

#237 채팅 개선, 커피챗 및 QnA 일부 UI 수정
  package.json
  pnpm-lock.yaml
  public/coffee.png
  src/app/chat/_components/ChatError.tsx
  src/app/chat/_components/Layout.tsx
  src/app/chat/layout.tsx
  src/app/globals.css
  src/app/profile/[id]/_components/deleteMember/DeleteMemberModalHeader.tsx
  src/app/profile/[id]/_components/deleteMember/steps/SubmitStep.tsx
  src/components/form/LoginForm.tsx
  src/components/layout/PopupEventListener.tsx
  src/components/layout/header/UserArea.tsx
  src/components/shared/page-template/ListPage.tsx
  src/components/shared/qna/OneQnA.tsx
  src/components/shared/time/PostTime.tsx
  src/components/shared/user/Profile.tsx
  src/components/shared/user/UserInfo.tsx
  src/hooks/chat/useChatRoomActive.tsx
  src/page/coding-meetings/detail/DetailPage.tsx
  src/page/coding-meetings/detail/comment/Comments.tsx
  src/page/coding-meetings/main/coding-meeting-list/CodingMeetingList.tsx
  src/page/coding-meetings/main/coding-meeting-list/CodingMeetingListContainer.tsx
  src/page/coding-meetings/main/info-area/CoffeeChatInfoArea.tsx
  src/page/coffee-chat/chat/ChatRoom.tsx
  src/page/coffee-chat/chat/ChatRoomHeader.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailHeader.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
  src/page/coffee-chat/main/CoffeeChatList.tsx
  src/page/coffee-chat/main/CoffeeChatListContainer.tsx
  src/page/coffee-chat/main/CoffeeChatMainPage.tsx
  src/page/coffee-chat/main/CoffeeChatWelcome.tsx
  src/page/coffee-chat/main/CupAnimation.tsx
  src/page/qna/components/QnAList.tsx
  src/page/qna/components/QuestionListContainer.tsx
  src/recoil/atoms/popup/popupWindowAtom.tsx
  src/recoil/atoms/socket/socketAtom.tsx
  src/socket/client/MessageControl.tsx
  src/socket/client/Messages.tsx
  src/socket/client/SocketConnection.tsx
  src/util/chat/popup.ts
  src/util/chat/time.ts
Labels: fix, design

#240 fix: QnA리스트 멤버id
  src/page/qna/components/QnAList.tsx
Labels: fix

#241 QnA리스트 멤버 id 매핑 수정
  src/page/qna/components/QnAList.tsx
Labels: fix

#244 fix: popupStorage
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
Labels: fix

#245 fix: localStorage 초기화
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
  src/util/chat/popup.ts
Labels: fix

#246 localStorage 예외 케이스 추가
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
  src/util/chat/popup.ts
Labels: fix

#253 chore: 커피챗 Reservation 타입 수정
  src/interfaces/dto/coffee-chat/get-all-coffeechat-reservation.dto.ts
  src/mocks/db/coffee-chat.ts
  src/mocks/handler/coffee-chat.ts
Labels: fix

#248 fix: 버그리포트 피드백 반영
  src/assets/lottie/user-profile-not-found.json
  src/components/shared/animation/UserProfileNotFound.tsx
  src/constants/timeOptions.ts
  src/interfaces/answer.ts
  src/mocks/db/answers.ts
  src/mocks/handler/answer.ts
  src/page/coffee-chat/detail/CoffeeChatDetailHeader.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
  src/page/landing/Landing.tsx
  src/page/qna-detail/components/Answers/OneAnswer.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/user-profile/components/UserProfileApiErrorBoundary.tsx
Labels: fix

#254 chore: React-Toastify AutoClose 기본 설정 변경
  src/components/shared/toast/ToastContainer.tsx
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterChatRoomArea.tsx
  src/page/coffee-chat/detail/reservation/mentee/TimeOptions.tsx
  src/page/qna-detail/components/Answers/AnswerContentBox.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/qna-detail/hooks/useHandleMyAnswer.tsx
  src/page/qna-detail/hooks/useQnADetail.tsx
  src/page/user-profile/hooks/useIntroduction.tsx
  src/page/user-profile/hooks/useProfileImage.tsx
Labels: chore

#256 chore: 메시지 관련 상수 파일 분리
  src/app/chat/create/page.tsx
  src/app/coding-meetings/create/page.tsx
  src/components/shared/scroll-to-top/ScrollToTop.tsx
  src/constants/message.ts
  src/constants/message/button.ts
  src/constants/message/cancle.ts
  src/constants/message/error.ts
  src/constants/message/notification.ts
  src/constants/message/pending.ts
  src/constants/message/search.ts
  src/constants/message/success.ts
  src/constants/message/validation.ts
  src/page/askQuestion/components/AskQuestionForm.tsx
  src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
  src/page/coding-meetings/create/components/HashTagsSection.tsx
  src/page/coding-meetings/main/ScrollTopButton.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/create/components/HashTagsSection.tsx
  src/page/coffee-chat/create/components/TimeOptions.tsx
  src/page/coffee-chat/detail/CoffeeChatDetailHeader.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterChatRoomArea.tsx
  src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
  src/page/coffee-chat/detail/reservation/mentee/TimeOptions.tsx
  src/page/qna-detail/components/Answers/AnswerContentBox.tsx
  src/page/qna-detail/components/Answers/AnswerList.tsx
  src/page/qna-detail/components/Answers/HandleAnswerBox.tsx
  src/page/qna-detail/components/Answers/VoteBox.tsx
  src/page/qna-detail/components/Markdown/MdEditor.tsx
  src/page/qna-detail/components/MyAnswer.tsx
  src/page/qna-detail/components/Question/HandleQuestionBox.tsx
  src/page/qna-detail/components/SuccessModalContent.tsx
  src/page/qna-detail/hooks/useAnswerVote.tsx
  src/page/qna-detail/hooks/useHandleMyAnswer.tsx
  src/page/qna-detail/hooks/useHandleQuestion.tsx
  src/page/qna-detail/hooks/useQnADetail.tsx
  src/page/search/WithoutResult.tsx
  src/page/user-profile/components/introduction/Introduction.tsx
  src/page/user-profile/components/profileImage/ProfileImage.tsx
  src/page/user-profile/hooks/useIntroduction.tsx
  src/page/user-profile/hooks/useProfileImage.tsx
  src/recoil/atoms/user.tsx
  src/service/coding-meetings.ts
  src/service/question.ts
  src/util/checkFormValidation.ts
Labels: chore

#257 refactor: 커피챗 관련 수정 사항 반영
  src/constants/limitation.ts
  src/interfaces/answer.ts
  src/interfaces/dto/coffee-chat/coffeechat-reservation-detail.dto.ts
  src/interfaces/dto/coffee-chat/create-coffeechat-post.dto.ts
  src/interfaces/dto/coffee-chat/get-my-coffeechat-reservation.ts
  src/interfaces/dto/coffee-chat/make-reservation.dto.ts
  src/interfaces/dto/coffee-chat/update-coffeechat-post.dto.ts
  src/mocks/db/answers.ts
  src/mocks/db/coffee-chat.ts
  src/mocks/handler/answer.ts
  src/mocks/handler/coffee-chat.ts
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
  src/page/coffee-chat/create/CreateCoffeeChatReservationPage.types.ts
  src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
  src/page/coffee-chat/detail/reservation/mentee/ReservationForMentee.tsx
  src/page/coffee-chat/detail/reservation/mentee/TimeOptions.tsx
  src/page/coffee-chat/detail/reservation/mentor/ReservationForMentor.tsx
  src/page/landing/Landing.tsx
  src/page/qna-detail/components/Answers/HandleAnswerBox.tsx
  src/page/qna-detail/components/Answers/OneAnswer.tsx
  src/page/qna-detail/components/Answers/VoteBox.tsx
  src/page/qna-detail/hooks/useAnswerVote.tsx
  src/page/qna-detail/hooks/useQnADetail.tsx
  src/react-query/coffee-chat.ts
  src/service/coffee-chat.ts
Labels: Refactor

#261 QA 수정사항 반영
  package.json
  pnpm-lock.yaml
  src/components/icons/Icons.tsx
  src/components/shared/TextCounter.tsx
  src/components/shared/Truncate.tsx
  src/components/shared/input/Guideline.tsx
  src/components/ui/DropdownMenu.tsx
  src/hooks/coding-meeting/useCommentMutation.tsx
  src/page/coding-meetings/detail/DetailHeader.tsx
  src/page/coding-meetings/detail/comment/CommentContent.tsx
  src/page/coding-meetings/detail/comment/CommentControl.tsx
  src/page/coding-meetings/detail/comment/Comments.tsx
  src/page/coding-meetings/detail/comment/CommentsFilter.tsx
  src/page/coding-meetings/main/coding-meeting-list/CodingMeetingList.tsx
  src/page/signup/Signup.tsx
  src/util/filter/coding-meeting-comments.ts
  src/util/historySession/coding-meetings.ts
  src/util/validate.ts
Labels: Feature, fix

#262 QA 수정사항 merge
  package.json
  pnpm-lock.yaml
  src/components/icons/Icons.tsx
  src/components/shared/TextCounter.tsx
  src/components/shared/Truncate.tsx
  src/components/shared/input/Guideline.tsx
  src/components/ui/DropdownMenu.tsx
  src/hooks/coding-meeting/useCommentMutation.tsx
  src/page/coding-meetings/detail/DetailHeader.tsx
  src/page/coding-meetings/detail/comment/CommentContent.tsx
  src/page/coding-meetings/detail/comment/CommentControl.tsx
  src/page/coding-meetings/detail/comment/Comments.tsx
  src/page/coding-meetings/detail/comment/CommentsFilter.tsx
  src/page/coding-meetings/main/coding-meeting-list/CodingMeetingList.tsx
  src/page/signup/Signup.tsx
  src/util/filter/coding-meeting-comments.ts
  src/util/historySession/coding-meetings.ts
  src/util/validate.ts
Labels: Feature, fix

#273 [feat] 소셜로그인, 닉네임 수정
  mock-oauth-server.js
  package.json
  src/app/oauth/github/page.tsx
  src/app/profile/nickname/page.tsx
  src/components/SocialButton.tsx
  src/components/form/LoginForm.tsx
  src/components/shared/auth-modal/AuthGuardModal.tsx
  src/components/shared/auth-modal/OAuthGuardModal.tsx
  src/constants/layoutMeta.ts
  src/interfaces/dto/member/update-member-nickname.dto.ts
  src/mocks/db/user.ts
  src/mocks/handler/member.ts
  src/page/oauth/github/OAuthGithubRedirect.tsx
  src/page/oauth/github/OAuthGithubSuccess.tsx
  src/page/oauth/github/error/OAuthGithubError.tsx
  src/page/oauth/github/error/OAuthGithubErrorField.tsx
  src/page/oauth/github/error/OAuthGithubErrorWrapper.tsx
  src/page/oauth/github/error/OAuthGithubInternelError.tsx
  src/page/user-profile/components/UserProfileDropdownMenu.tsx
  src/page/user-profile/components/UserProfilePresenter.tsx
  src/page/user-profile/edit-nickname/EditNicknameCancel.tsx
  src/page/user-profile/edit-nickname/EditNicknamePage.tsx
  src/page/user-profile/edit-nickname/error/EditNicknameErrorFallback.tsx
  src/page/user-profile/edit-nickname/error/nicknameErrors.ts
  src/page/user-profile/edit-nickname/form/ConfirmStep.tsx
  src/page/user-profile/edit-nickname/form/EditNicknameForm.tsx
  src/page/user-profile/edit-nickname/form/InputStep.tsx
  src/page/user-profile/edit-nickname/form/SubmitStep.tsx
  src/page/user-profile/edit-nickname/loading/EditNicknameProgressLoading.tsx
  src/recoil/atoms/user.tsx
  src/service/member.ts
  src/service/route-map.ts
Labels: Feature

#276 개발서버 CI/CD
  .github/workflows/dev-cd-workflow.yml
  .github/workflows/dev-ci-workflow.yml
Labels: Setting

#287 fix: 닉네임 수정
  src/page/oauth/github/OAuthGithubSuccess.tsx
  src/page/user-profile/components/UserProfilePresenter.tsx
  src/page/user-profile/edit-nickname/form/SubmitStep.tsx
Labels: fix

#289 fix: 로그인 버튼
  src/components/form/LoginForm.tsx
Labels: fix

#294 [chore] 구글 서치 콘솔, 네이버 서치 어드바이저 사이트 소유 확인(main branch 반영)
  .github/workflows/ci-workflow.yml
  Dockerfile
  src/app/page.tsx
Labels: Infra, Setting

#295 [feat] SSE
  .github/workflows/ci-workflow.yml
  .github/workflows/dev-ci-workflow.yml
  Dockerfile
  mock-oauth-server.js
  mock-server.js
  package.json
  pnpm-lock.yaml
  src/components/layout/header/UserArea.tsx
  src/components/layout/header/alerm/Alerm.tsx
  src/hooks/sse/useSSE.tsx
  src/interfaces/sse.ts
  src/mocks/handler/answer.ts
  src/service/sse.ts
Labels: Feature, Setting

#299 알림 개선 메인 반영
  src/app/notification/page.tsx
  src/components/layout/header/alerm/Alerm.tsx
  src/components/shared/page-template/ListPage.tsx
  src/constants/layoutMeta.ts
  src/constants/sse/sse-constants.ts
  src/interfaces/dto/sse/get-alret-list.ts
  src/interfaces/sse.ts
  src/mocks/handler/answer.ts
  src/page/notification/NotificationPage.tsx
  src/page/notification/error/NotificationError.tsx
  src/page/notification/list/NotificationList.tsx
  src/page/notification/list/NotificationListContainer.tsx
  src/recoil/atoms/sse/sseAtom.tsx
  src/service/axios.ts
  src/service/route-map.ts
  src/service/sse.ts
Labels: Feature, fix

#300 refactor: useSSE
  src/components/layout/header/alerm/Alerm.tsx
  src/hooks/sse/useSSE.tsx
Labels: Refactor

#301 SEO 개선
  public/og.png
  src/app/coding-meetings/[token]/page.tsx
  src/app/layout.tsx
  src/app/robots.txt
  src/app/sitemap.ts
  src/interfaces/dto/seo/get-coding-meeting-seo-list.ts
  src/interfaces/dto/seo/get-qna-seo-list.ts
  src/service/seo.ts
Labels: Refactor, Setting

#302 SSE hook개선, SEO개선
  public/og.png
  src/app/coding-meetings/[token]/page.tsx
  src/app/layout.tsx
  src/app/robots.txt
  src/app/sitemap.ts
  src/components/layout/header/alerm/Alerm.tsx
  src/hooks/sse/useSSE.tsx
  src/interfaces/dto/seo/get-coding-meeting-seo-list.ts
  src/interfaces/dto/seo/get-qna-seo-list.ts
  src/service/seo.ts
Labels: Refactor, Setting

#304 chore: 모든 페이지 og, twitter card 적용
  src/app/chat/[id]/page.tsx
  src/app/chat/create/page.tsx
  src/app/chat/page.tsx
  src/app/chat/room/[id]/page.tsx
  src/app/chat/u/[id]/page.tsx
  src/app/coding-meetings/[token]/page.tsx
  src/app/coding-meetings/create/page.tsx
  src/app/coding-meetings/page.tsx
  src/app/coding-meetings/post/[token]/page.tsx
  src/app/faq/page.tsx
  src/app/layout.tsx
  src/app/notification/page.tsx
  src/app/page.tsx
  src/app/profile/[id]/page.tsx
  src/app/profile/nickname/page.tsx
  src/app/qna/page.tsx
  src/app/question/[id]/page.tsx
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/constants/layoutMeta.ts
Labels: Refactor

#305 chore: 모든 페이지 og, twitter card 적용(main)
  src/app/chat/[id]/page.tsx
  src/app/chat/create/page.tsx
  src/app/chat/page.tsx
  src/app/chat/room/[id]/page.tsx
  src/app/chat/u/[id]/page.tsx
  src/app/coding-meetings/[token]/page.tsx
  src/app/coding-meetings/create/page.tsx
  src/app/coding-meetings/page.tsx
  src/app/coding-meetings/post/[token]/page.tsx
  src/app/faq/page.tsx
  src/app/layout.tsx
  src/app/notification/page.tsx
  src/app/page.tsx
  src/app/profile/[id]/page.tsx
  src/app/profile/nickname/page.tsx
  src/app/qna/page.tsx
  src/app/question/[id]/page.tsx
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/constants/layoutMeta.ts
Labels: Refactor

#308 fix: 질문이미지를 og, twitter 에 반영
  src/app/question/[id]/page.tsx
Labels: fix

#310 질문 og, twitter 와 깃허브 로그인 에러 페이지 수정
  src/app/oauth/github/page.tsx
  src/app/question/[id]/page.tsx
  src/page/oauth/github/error/OAuthGithubError.tsx
  src/page/oauth/github/error/OAuthGithubErrorWrapper.tsx
Labels: fix
